const nombre = "Luis"
const apellido = "Pinto"
const estudiante = nombre.concat(" ", apellido)
const estudianteMayus = estudiante.toUpperCase()
const estudianteMinus = estudiante.toLowerCase()
const length = estudiante.length
const inicialNombre = nombre.substring(0, 1)
const finalApellido = apellido.substring(apellido.length - 1, apellido.length)
const estudianteSinEspacios = estudiante.replace(/ /g, "")
const nombreEstudiante = estudiane.includes(nombre)
